### ISSUE TITLE
Timed out connecting to server

### ISSUE THREAD

**Issue by alessandrostein** [raniellyferreira/economy-api#3]
Hi guys,

Recently I've been using in production this API for currency conversion.

`http://economia.awesomeapi.com.br/USD-BRLT/1`

In the past few days, had been working very well but today we have some time out in the request.

```
irb(main):018:0> response = RestClient.get "http://economia.awesomeapi.com.br/USD-BRLT/1"
RestClient::Exceptions::OpenTimeout: Timed out connecting to server
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:731:in `rescue in transmit'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:647:in `transmit'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
	from (irb):18
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/alessandrostein/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

In the same time, using the webpage, I have the result expected.

<img width="743" alt="captura de tela 2018-11-01 as 15 22 46" src="https://user-images.githubusercontent.com/4340946/47871140-0e7da080-ddea-11e8-9606-8bb61937c96a.png">

Someone can help me?

**Comment by raniellyferreira** [comment]
Hello, sorry for the lack of response. Platform migration was being done at the time.
